worker_processes auto;
events { worker_connections 8192; }

http {
    # RATE LIMITING (REQUESTS)
    # limit_req_zone $binary_remote_addr zone=flask_limit:10m rate=5r/s;
    # limit_req_zone $binary_remote_addr zone=node_limit:10m rate=10r/s;
    



    # KEEPALIVE POOL
    upstream bank_backend {
        server bank-target:5000; 
        keepalive 128; 
    }
    upstream bank_memory_backend { 
        server bank-memory:5002; 
        keepalive 128; 
    }
    upstream bank_node_backend { 
        server bank-node-target:5003; 
        keepalive 128; 
    }





    
    server {
        listen 5000 ssl http2;
        http2_max_concurrent_streams 128;
        ssl_certificate /etc/nginx/ssl/server.crt;
        ssl_certificate_key /etc/nginx/ssl/server.key;

        location / {
            # RATE LIMITING (REQUESTS)
            # limit_req zone=flask_limit burst=10 nodelay;
            
            
            proxy_pass http://bank_backend;
            proxy_http_version 1.1;
            proxy_set_header Connection ""; 
            

            proxy_buffering on;
        }
    }

    server {
        listen 5002 ssl http2;
        http2_max_concurrent_streams 128;
        ssl_certificate /etc/nginx/ssl/server.crt;
        ssl_certificate_key /etc/nginx/ssl/server.key;

        location / {
            proxy_pass http://bank_memory_backend;
            proxy_http_version 1.1;
            proxy_set_header Connection ""; 
            proxy_buffering on;
        }
    }

    server {
        listen 5003 ssl http2;
        http2_max_concurrent_streams 128;
        ssl_certificate /etc/nginx/ssl/server.crt;
        ssl_certificate_key /etc/nginx/ssl/server.key;

        location / {
            # limit_req zone=node_limit;

            proxy_pass http://bank_node_backend;
            proxy_http_version 1.1;
            proxy_set_header Connection ""; 
            proxy_buffering on;
        }
    }

}